// @ts-nocheck
import { isSupabaseConfigured } from './supabase.js'
import * as live from './api.live.js'
import * as demo from './api.demo.js'

const api = isSupabaseConfigured ? live : demo

export const fetchAll = (...args) => api.fetchAll(...args)
export const addSetAside = (...args) => api.addSetAside(...args)
export const removeSetAside = (...args) => api.removeSetAside(...args)
export const addBalanceEntry = (...args) => api.addBalanceEntry(...args)
export const adjustAccountBalance = (...args) => api.adjustAccountBalance(...args)
export const addAccount = (...args) => api.addAccount(...args)
export const updateAccount = (...args) => api.updateAccount(...args)
export const setAccountOrder = (...args) => api.setAccountOrder(...args)
export const deleteAccount = (...args) => api.deleteAccount(...args)
export const addTransaction = (...args) => api.addTransaction(...args)
export const updateTransaction = (...args) => api.updateTransaction(...args)
export const deleteTransaction = (...args) => api.deleteTransaction(...args)
export const setTransactionCategories = (...args) => api.setTransactionCategories(...args)
export const setIncomeSources = (...args) => api.setIncomeSources(...args)
export const addBill = (...args) => api.addBill(...args)
export const updateBill = (...args) => api.updateBill(...args)
export const deleteBill = (...args) => api.deleteBill(...args)
export const setBillSmooth = (...args) => api.setBillSmooth(...args)
export const setDebtSmooth = (...args) => api.setDebtSmooth(...args)
export const setDebtActive = (...args) => api.setDebtActive(...args)
export const moveToSmoothing = (...args) => api.moveToSmoothing(...args)
export const upsertBudget = (...args) => api.upsertBudget(...args)
export const deleteBudget = (...args) => api.deleteBudget(...args)
export const renameBudget = (...args) => api.renameBudget(...args)
export const setTransactionsCategory = (...args) => api.setTransactionsCategory(...args)
export const upsertCategoryAlias = (...args) => api.upsertCategoryAlias(...args)
export const saveSettings = (...args) => api.saveSettings(...args)
export const saveNotificationPrefs = (...args) => api.saveNotificationPrefs(...args)
export const addPushSubscription = (...args) => api.addPushSubscription(...args)
export const removePushSubscription = (...args) => api.removePushSubscription(...args)
export const addIncome = (...args) => api.addIncome(...args)
export const updateIncome = (...args) => api.updateIncome(...args)
export const deleteIncome = (...args) => api.deleteIncome(...args)
export const addGoal = (...args) => api.addGoal(...args)
export const updateGoalCurrent = (...args) => api.updateGoalCurrent(...args)
export const setGoalReserved = (...args) => api.setGoalReserved(...args)
export const incrementGoalCurrent = (...args) => api.incrementGoalCurrent(...args)
export const decrementDebtBalance = (...args) => api.decrementDebtBalance(...args)
export const addDebtPayment = (...args) => api.addDebtPayment(...args)
export const deleteDebtPayment = (...args) => api.deleteDebtPayment(...args)
export const updateGoal = (...args) => api.updateGoal(...args)
export const deleteGoal = (...args) => api.deleteGoal(...args)
export const addDebt = (...args) => api.addDebt(...args)
export const updateDebtBalance = (...args) => api.updateDebtBalance(...args)
export const updateDebtCredit = (...args) => api.updateDebtCredit(...args)
export const addCreditScore = (...args) => api.addCreditScore(...args)
export const deleteCreditScore = (...args) => api.deleteCreditScore(...args)
export const toggleMilestone = (...args) => api.toggleMilestone(...args)
export const toggleCreditTask = (...args) => api.toggleCreditTask(...args)
export const updateDebt = (...args) => api.updateDebt(...args)
export const deleteDebt = (...args) => api.deleteDebt(...args)
export const addPhase = (...args) => api.addPhase(...args)
export const updatePhase = (...args) => api.updatePhase(...args)
export const deletePhase = (...args) => api.deletePhase(...args)
export const addBucket = (...args) => api.addBucket(...args)
export const updateBucketCurrent = (...args) => api.updateBucketCurrent(...args)
export const deleteBucket = (...args) => api.deleteBucket(...args)
